version:  '3.7'

networks:
  gateway-network:
    external: true

services:
    converter_app:
        build:
            context: ./
        volumes:
                - ./:/app
        expose:
                - "5000"
        networks:
            - gateway-network
