version:  '3.7'

networks:
  demo:
    external: true

services:
    converter_app:
        build:
            context: ./
        volumes:
                - ./:/app
        expose:
                - "5000"
        networks:
            - demo

    converter_nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./:/var/www
        expose:
            - "80"
        networks:
            - demo
